export enum DiscussionErrorCode {
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  ROOM_ACCESS_DENIED = 'ROOM_ACCESS_DENIED',
  ROOM_READ_ONLY = 'ROOM_READ_ONLY',
  MESSAGE_CONTENT_INVALID = 'MESSAGE_CONTENT_INVALID',
  ANNOUNCEMENT_NOT_ALLOWED = 'ANNOUNCEMENT_NOT_ALLOWED',
  REGISTRATION_NOT_FOUND = 'REGISTRATION_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
